---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tushar
  labels:
    app: backend
spec:
  template:
    metadata:
      labels:
        app: tush-backend
    spec:
      containers:
      - name: tushar
        image: httpd
        ports:
        - containerPort: 80
  selector:
    app: tush-backend
  replicas: 3
---  